"""init

Revision ID: 22a3b527b18e
Revises: 
Create Date: 2026-01-22 20:54:24.200083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a3b527b18e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('send_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('reserved_at', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'target_date', 'kind', name='uq_send_log')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_chat_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=False),
    sa.Column('morning_time', sa.Text(), nullable=False),
    sa.Column('evening_time', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.Text(), nullable=True),
    sa.Column('date_from', sa.Text(), nullable=True),
    sa.Column('date_to', sa.Text(), nullable=True),
    sa.Column('rows_count', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Text(), nullable=False),
    sa.Column('end_time', sa.Text(), nullable=False),
    sa.Column('room', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('teacher', sa.Text(), nullable=True),
    sa.Column('source_upload_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_date', 'schedule_items', ['date'], unique=False)
    op.create_index('idx_schedule_date_start', 'schedule_items', ['date', 'start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_schedule_date_start', table_name='schedule_items')
    op.drop_index('idx_schedule_date', table_name='schedule_items')
    op.drop_table('schedule_items')
    op.drop_table('uploads')
    op.drop_table('settings')
    op.drop_table('send_log')
    # ### end Alembic commands ###
